from fpdf import FPDF
import datetime

def generate_pdf(result: dict) -> bytes:
    def safe(text):
        if not text:
            return ""
        return str(text).encode('ascii', 'ignore').decode('ascii')

    pdf = FPDF()
    pdf.add_page()
    pdf.set_margins(20, 20, 20)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(45, 106, 79)
    pdf.cell(0, 12, "PlantMD - Disease Detection Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 7, f"Generated: {datetime.datetime.now().strftime('%d %B %Y %H:%M')}", ln=True, align="C")
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Diagnosis: {safe(result.get('disease_name', 'Unknown'))}", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(60, 8, f"Severity: {safe(result.get('severity', 'N/A'))}")
    pdf.cell(60, 8, f"Confidence: {result.get('confidence', 0)}%")
    pdf.cell(60, 8, f"Urgency: {safe(result.get('urgency', 'N/A'))}", ln=True)
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(45, 106, 79)
    pdf.cell(0, 9, "Observation:", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 7, safe(result.get("description", "")))
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(45, 106, 79)
    pdf.cell(0, 9, "Treatments:", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)
    for t in result.get("treatments", []):
        pdf.multi_cell(0, 7, f"  - {safe(t)}")
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(45, 106, 79)
    pdf.cell(0, 9, "Causes:", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)
    for c in result.get("causes", []):
        pdf.multi_cell(0, 7, f"  - {safe(c)}")
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(45, 106, 79)
    pdf.cell(0, 9, "Prevention:", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 11)
    for p in result.get("prevention", []):
        pdf.multi_cell(0, 7, f"  - {safe(p)}")
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "PlantMD | AI Plant Disease Detection | Master Thesis Project", align="C")
    return bytes(pdf.output())
